[package]
name = "crypto_final"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = { version = "0.4.0", features = ["rand"] }
num-bigint = "0.4.3"
num-traits = "0.2.15"
requestty = "0.5.0"
